name: pr
on: pull_request
jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: echo "TERM=xterm" >> $GITHUB_ENV
      - run: sbt clean 'console/testOnly io.joern.console.cpgqlserver.CPGQLServerTests'
      - run: cat /tmp/ammonite-test
